### ISSUE TITLE
Getting started?

### ISSUE THREAD

**Issue by computersrmyfriends** [gentry-atkinson/Robot-Podcast-Generator#1]
There's no requirements.txt.

How to setup and get it running?

**Comment by computersrmyfriends** [comment]
Got Started with this:

diffusers==0.27.2
numpy==1.26.4
scipy==1.13.0
torch==2.2.0
transformers==4.39.3

![image](https://github.com/gentry-atkinson/Robot-Podcast-Generator/assets/323931/80f09ee9-9205-41f7-8ba5-8e4c4d0384b0)


Hope it completes the process.

**Comment by computersrmyfriends** [comment]
Nice efforts. 🙏👍

**Comment by gentry-atkinson** [comment]
Yeah, things are pretty barebones right now. I'll put a requirements doc on my TODO. Thanks for putting in the effort to get it running. Hope it works for you!

**Comment by computersrmyfriends** [comment]
It stopped after a while for me on a A4000 with 16G VRAM gpu

![image](https://github.com/gentry-atkinson/Robot-Podcast-Generator/assets/323931/ec6c3623-d325-4b9e-bfed-431cf0fa36f6)

**Comment by computersrmyfriends** [comment]
Finally, it went through and got stuck here:

```
sing the model-agnostic default `max_length` (=1500) to control the generation length. We recommend setting `max_new_tokens` to control the maximum length of the generation.
Traceback (most recent call last):
  File "/root/vworkspace/Robot-Podcast-Generator/main.py", line 148, in <module>
    generate_theme_song()
  File "/root/vworkspace/Robot-Podcast-Generator/gen_music.py", line 21, in generate_theme_song
    scipy.io.wavfile.write(
  File "/opt/conda/lib/python3.10/site-packages/scipy/io/wavfile.py", line 766, in write
    fid = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'Podcast Generator/tunes/themesong.wav'
```
After another try, it's something else.
Is something missing? Maybe it didn't generate the themesong.wav?

**Comment by gentry-atkinson** [comment]
Looks like it was a directory naming issue. generate_theme_song was trying to write to "Podcast Generator" which is an old name for this repo. I just pushed a fix. Thanks for finding that.

I'm surprised that an A4000 struggled with the image generator, although that is admittedly a hungry boy. If you have similar struggles in the future, try editing line 24 of gen_img where the logo is scaled up to 1400x1400 (a recommended size for podcast banners). You can comment that out or just scale the image up to a smaller size like 700x700.
